#!/bin/bash

###########
#####
#   Dummypkg
#####
###########

DUMMYVERSION="0.6"

## Script to install dummy packages in pacman
## Use at own risk!

TMPDIR="/tmp/dummy-temp"

# I want to be privilege-elevation agnostic.
function elevate() {
	if [ "$EUID" -eq 0 ]; then
		"$@"
	elif command -v sudo >/dev/null 2>&1; then
		sudo "$@"
	elif command -v doas >/dev/null 2>&1; then
		doas "$@"
	elif command -v run0 >/dev/null 2>&1; then
		run0 "$@"
	elif command -v su >/dev/null 2>&1; then
		echo "Root"
		su -c "$(printf '%q ' "$@")"
	else
		echo "Error: no privilege escalation tool found."
		echo "Supported tools: sudo, doas, run0 or su."
		exit 1
	fi
}


function install(){

	# Remove previous temporary build directory for this package
	if [ -d "$TMPDIR/$PACKAGE" ]; then
		rm -rf "$TMPDIR/$PACKAGE"
	fi

	# Create temporary build directory
	mkdir -p "$TMPDIR/$PACKAGE" || exit 1

	# Generate PKGBUILD
	cat > "$TMPDIR/$PACKAGE/PKGBUILD" <<EOF
pkgname=$PACKAGE
pkgver=$PKGVER
pkgrel=1
pkgdesc="Dummy package created by dummypkg"
arch=(any)
provides=($PACKAGE=$PKGVER)

package() {
	install -Dm644 /dev/null "\$pkgdir/usr/share/dummypkg/\$pkgname"
}
EOF

	# Enter build directory
	cd "$TMPDIR/$PACKAGE/" || exit 1

	# Build package
	makepkg || {
		rm -rf "$TMPDIR/$PACKAGE"
		exit 1
	}

	# Install package
	elevate pacman -U "$TMPDIR/$PACKAGE"/*pkg.tar.zst || {
		rm -rf "$TMPDIR/$PACKAGE"
		exit 1
	}

	# Remove temporary files
	rm -rf "$TMPDIR/$PACKAGE"

	exit 0
}

function remove(){

	# Check whether package is installed
	if ! pacman -Q "$RPACKAGE" >/dev/null 2>&1; then
		echo "'$RPACKAGE' is not installed."
		exit 1
	fi

	# Check whether package is registered as a dummy package
	if [ ! -e "/usr/share/dummypkg/$RPACKAGE" ]; then
		echo "'$RPACKAGE' is not a dummy package."
		exit 1
	fi

	# Remove package and its files through pacman
	elevate pacman -R "$RPACKAGE"

	exit 0
}


function list(){
	if [ ! -d /usr/share/dummypkg ]; then
		exit 0
	fi

	for file in `ls /usr/share/dummypkg -1`
	do
		echo "$(pacman -Q $file)"
	done

	exit 0
}


function usage(){
	echo "Version $DUMMYVERSION"
	echo "usage: dummypkg [[--install] [--list] [--help] [--remove]]"
	echo
	echo "Options:"
	echo "  -S, --install PACKAGE VERSION   Install a dummy package"
	echo "  -R, --remove PACKAGE            Remove a dummy package"
	echo "  -l, --list                      List installed dummy packages"
	echo "  -h, --help                      Show this help"

	exit 0
}


INSTALL=0
REMOVE=0
LIST=0


if [ "$1" = "" ]; then
	usage
	exit 1
fi


while [ "$1" != "" ]; do

	case "$1" in

		-S | --install )

			INSTALL=1
			PACKAGE="$2"
			PKGVER="$3"

			if [ -z "$PACKAGE" ]; then
				echo "--install requires a package name"
				exit 1
			fi

			if [[ ! "$PACKAGE" =~ ^[a-zA-Z0-9@._+:-]+$ ]]; then
				echo "Invalid package name: '$PACKAGE'"
				echo "Package names may only contain letters, numbers, @, ., _, +, :, and -."
				exit 1
			fi

			if [ -z "$PKGVER" ]; then
				echo "--install requires a package version"
				exit 1
			fi

			shift
			shift
			;;


		-R | --remove )

			REMOVE=1
			RPACKAGE="$2"

			if [ -z "$RPACKAGE" ]; then
				echo "--remove requires a package name"
				exit 1
			fi

			shift
			;;


		-h | --help )

			usage
			exit 0
			;;


		-l | --list )

			LIST=1
			;;


		* )

			usage
			exit 1
			;;

	esac

	shift

done


if [ "$INSTALL" = 1 ]; then
	install
fi

if [ "$REMOVE" = 1 ]; then
	remove
fi

if [ "$LIST" = 1 ]; then
	list
fi
